In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import os
os.chdir(r"C:\Users\komal\Netflix-Recommendation-System")

In [6]:
os.listdir()

['Data']

In [7]:
os.listdir()

['Data', 'recommendation_system.ipynb']

In [8]:
import pandas as pd

ratings = pd.read_csv(
    "Data/u.data",
    sep="\t",
    names=["user_id","movie_id","rating","timestamp"]
)

ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [9]:
movies = pd.read_csv(
    "Data/u.item",
    sep="|",
    encoding="latin-1",
    names=[
        "movie_id","title","release_date","video_release_date",
        "IMDb_URL","unknown","Action","Adventure","Animation",
        "Children","Comedy","Crime","Documentary","Drama",
        "Fantasy","Film-Noir","Horror","Musical","Mystery",
        "Romance","Sci-Fi","Thriller","War","Western"
    ]
)

movies.head()

,movie_id,title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [10]:
data = pd.merge(ratings, movies, on="movie_id")

data.head()

,user_id,movie_id,rating,timestamp,title,release_date,video_release_date,IMDb_URL,unknown,Action,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,196,242,3,881250949,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996),0,0,...,0,0,0,0,0,0,0,0,0,0
1,186,302,3,891717742,L.A. Confidential (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?L%2EA%2E+Conf...,0,0,...,0,1,0,0,1,0,0,1,0,0
2,22,377,1,878887116,Heavyweights (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Heavyweights%...,0,0,...,0,0,0,0,0,0,0,0,0,0
3,244,51,2,880606923,Legends of the Fall (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Legends%20of%...,0,0,...,0,0,0,0,0,1,0,0,1,1
4,166,346,1,886397596,Jackie Brown (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-11...,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
movie_ratings = data.pivot_table(
    index="user_id",
    columns="title",
    values="rating"
)

movie_ratings.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN

In [12]:
movie_ratings.shape

(943, 1664)

In [13]:
movie_ratings.isnull().sum().head()

title
'Til There Was You (1997)    934
1-900 (1994)                 938
101 Dalmatians (1996)        834
12 Angry Men (1957)          818
187 (1997)                   902
dtype: int64

In [14]:
toy_story_ratings = movie_ratings["Toy Story (1995)"]

toy_story_ratings.head()

user_id
1    5.0
2    4.0
3    NaN
4    NaN
5    4.0
Name: Toy Story (1995), dtype: float64

In [15]:
similar_movies = movie_ratings.corrwith(toy_story_ratings)

C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2991: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [16]:
corr_toy_story = pd.DataFrame(similar_movies, columns=["Correlation"])
corr_toy_story.dropna(inplace=True)
corr_toy_story.head()

                             Correlation
title
'Til There Was You (1997)       0.534522
101 Dalmatians (1996)           0.232118
12 Angry Men (1957)             0.334943
187 (1997)                      0.651857
2 Days in the Valley (1996)     0.162728

In [17]:
ratings_count = data.groupby("title")["rating"].count()
corr_toy_story["num_ratings"] = ratings_count
corr_toy_story.head()

                             Correlation  num_ratings
title
'Til There Was You (1997)       0.534522            9
101 Dalmatians (1996)           0.232118          109
12 Angry Men (1957)             0.334943          125
187 (1997)                      0.651857           41
2 Days in the Valley (1996)     0.162728           93

In [18]:
recommendations = corr_toy_story[corr_toy_story["num_ratings"] > 100] \
                    .sort_values("Correlation", ascending=False)

recommendations.head(10)

                               Correlation  num_ratings
title
Toy Story (1995)                  1.000000          452
Craft, The (1996)                 0.549100          104
Down Periscope (1996)             0.457995          101
Miracle on 34th Street (1994)     0.456291          101
G.I. Jane (1997)                  0.454756          175
Amistad (1997)                    0.449915          124
Beauty and the Beast (1991)       0.442960          202
Mask, The (1994)                  0.432855          129
Cinderella (1950)                 0.428372          129
That Thing You Do! (1996)         0.427936          176

In [21]:
def recommend_movies(movie_name):

   

    movie_user_ratings = movie_ratings[movie_name]

    similar_movies = movie_ratings.corrwith(movie_user_ratings)

    corr_df = pd.DataFrame(similar_movies, columns=["Correlation"])
    corr_df.dropna(inplace=True)

    ratings_count = data.groupby("title")["rating"].count()
    corr_df["num_ratings"] = ratings_count

    recommendations = corr_df[corr_df["num_ratings"] > 100] \
                        .sort_values("Correlation", ascending=False)

    return recommendations.head(10)

In [22]:
recommend_movies("Toy Story (1995)")

C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2991: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

                               Correlation  num_ratings
title
Toy Story (1995)                  1.000000          452
Craft, The (1996)                 0.549100          104
Down Periscope (1996)             0.457995          101
Miracle on 34th Street (1994)     0.456291          101
G.I. Jane (1997)                  0.454756          175
Amistad (1997)                    0.449915          124
Beauty and the Beast (1991)       0.442960          202
Mask, The (1994)                  0.432855          129
Cinderella (1950)                 0.428372          129
That Thing You Do! (1996)         0.427936          176

In [24]:
def recommend_movies(movie_name):

    movie_user_ratings = movie_ratings[movie_name]

    similar_movies = movie_ratings.corrwith(movie_user_ratings)

    corr_df = pd.DataFrame(similar_movies, columns=["Correlation"])
    corr_df.dropna(inplace=True)

    ratings_count = data.groupby("title")["rating"].count()
    corr_df["num_ratings"] = ratings_count

    recommendations = corr_df[corr_df["num_ratings"] > 100] \
                        .sort_values("Correlation", ascending=False)

    # ✅ REMOVE SAME MOVIE
    recommendations = recommendations.drop(movie_name)

    return recommendations.head(10)

In [25]:
recommend_movies("Toy Story (1995)")

C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2991: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\komal\anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

                               Correlation  num_ratings
title
Craft, The (1996)                 0.549100          104
Down Periscope (1996)             0.457995          101
Miracle on 34th Street (1994)     0.456291          101
G.I. Jane (1997)                  0.454756          175
Amistad (1997)                    0.449915          124
Beauty and the Beast (1991)       0.442960          202
Mask, The (1994)                  0.432855          129
Cinderella (1950)                 0.428372          129
That Thing You Do! (1996)         0.427936          176
Lion King, The (1994)             0.426778          220